eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:123456@localhost:8900/eureka/
server:
  port: 8902
spring:
  application:
    name: ribbon-consumer